# Generated by Django 3.2.4 on 2021-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroIdentificacion', models.CharField(max_length=9)),
                ('NombreProveedor', models.CharField(max_length=150)),
                ('TelefonoProveedor', models.IntegerField()),
                ('DireccionProveedor', models.CharField(max_length=200)),
                ('EmailProveedor', models.CharField(max_length=100)),
                ('PaisProveedor', models.CharField(max_length=20)),
                ('ContraseñaProveedor', models.CharField(max_length=90)),
            ],
        ),
    ]
